### ISSUE TITLE
Errors with python 2.7

### ISSUE THREAD

**Issue by ddokleja** [d7networks/nagios#2]
Hello,

your script does not work with python 2.7:

`  File "d7sms.py", line 102
    print(f"Failed to send sms, reason: {e.reason}, code: {e.code} ")
                                                                   ^
SyntaxError: invalid syntax`

There seem to be an error in syntax, so changed line:
`print(f"Failed to send sms, reason: {e.reason}, code: {e.code} ")`
with:
`print("Failed to send sms, reason: {e.reason}, code: {e.code} ")` (removed f)

Then after this fix:
`Traceback (most recent call last):
  File "d7sms.py", line 49, in <module>
    import urllib.request
ImportError: No module named request`

Changed line:
`import urllib.request`
with 
`from six.moves import urllib`

And then the script works

**Comment by mknithin** [comment]
Hi @ddokleja , thanks for the effort . existing plugin supports python3 version . let us check the feasibility to include support for python2 .
